package com.example.lenovo.zuoye1119.db;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.example.lenovo.zuoye1119.beans.DatasBean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "DATAS_BEAN".
*/
public class DatasBeanDao extends AbstractDao<DatasBean, Long> {

    public static final String TABLENAME = "DATAS_BEAN";

    /**
     * Properties of entity DatasBean.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property ApkLink = new Property(0, String.class, "apkLink", false, "APK_LINK");
        public final static Property Audit = new Property(1, int.class, "audit", false, "AUDIT");
        public final static Property Author = new Property(2, String.class, "author", false, "AUTHOR");
        public final static Property ChapterId = new Property(3, int.class, "chapterId", false, "CHAPTER_ID");
        public final static Property ChapterName = new Property(4, String.class, "chapterName", false, "CHAPTER_NAME");
        public final static Property Collect = new Property(5, boolean.class, "collect", false, "COLLECT");
        public final static Property CourseId = new Property(6, int.class, "courseId", false, "COURSE_ID");
        public final static Property Desc = new Property(7, String.class, "desc", false, "DESC");
        public final static Property EnvelopePic = new Property(8, String.class, "envelopePic", false, "ENVELOPE_PIC");
        public final static Property Fresh = new Property(9, boolean.class, "fresh", false, "FRESH");
        public final static Property Id = new Property(10, Long.class, "id", true, "_id");
        public final static Property Link = new Property(11, String.class, "link", false, "LINK");
        public final static Property NiceDate = new Property(12, String.class, "niceDate", false, "NICE_DATE");
        public final static Property NiceShareDate = new Property(13, String.class, "niceShareDate", false, "NICE_SHARE_DATE");
        public final static Property Origin = new Property(14, String.class, "origin", false, "ORIGIN");
        public final static Property Prefix = new Property(15, String.class, "prefix", false, "PREFIX");
        public final static Property ProjectLink = new Property(16, String.class, "projectLink", false, "PROJECT_LINK");
        public final static Property PublishTime = new Property(17, long.class, "publishTime", false, "PUBLISH_TIME");
        public final static Property SelfVisible = new Property(18, int.class, "selfVisible", false, "SELF_VISIBLE");
        public final static Property ShareDate = new Property(19, long.class, "shareDate", false, "SHARE_DATE");
        public final static Property ShareUser = new Property(20, String.class, "shareUser", false, "SHARE_USER");
        public final static Property SuperChapterId = new Property(21, int.class, "superChapterId", false, "SUPER_CHAPTER_ID");
        public final static Property SuperChapterName = new Property(22, String.class, "superChapterName", false, "SUPER_CHAPTER_NAME");
        public final static Property Title = new Property(23, String.class, "title", false, "TITLE");
        public final static Property Type = new Property(24, int.class, "type", false, "TYPE");
        public final static Property UserId = new Property(25, int.class, "userId", false, "USER_ID");
        public final static Property Visible = new Property(26, int.class, "visible", false, "VISIBLE");
        public final static Property Zan = new Property(27, int.class, "zan", false, "ZAN");
    }


    public DatasBeanDao(DaoConfig config) {
        super(config);
    }
    
    public DatasBeanDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"DATAS_BEAN\" (" + //
                "\"APK_LINK\" TEXT," + // 0: apkLink
                "\"AUDIT\" INTEGER NOT NULL ," + // 1: audit
                "\"AUTHOR\" TEXT," + // 2: author
                "\"CHAPTER_ID\" INTEGER NOT NULL ," + // 3: chapterId
                "\"CHAPTER_NAME\" TEXT," + // 4: chapterName
                "\"COLLECT\" INTEGER NOT NULL ," + // 5: collect
                "\"COURSE_ID\" INTEGER NOT NULL ," + // 6: courseId
                "\"DESC\" TEXT," + // 7: desc
                "\"ENVELOPE_PIC\" TEXT," + // 8: envelopePic
                "\"FRESH\" INTEGER NOT NULL ," + // 9: fresh
                "\"_id\" INTEGER PRIMARY KEY ," + // 10: id
                "\"LINK\" TEXT," + // 11: link
                "\"NICE_DATE\" TEXT," + // 12: niceDate
                "\"NICE_SHARE_DATE\" TEXT," + // 13: niceShareDate
                "\"ORIGIN\" TEXT," + // 14: origin
                "\"PREFIX\" TEXT," + // 15: prefix
                "\"PROJECT_LINK\" TEXT," + // 16: projectLink
                "\"PUBLISH_TIME\" INTEGER NOT NULL ," + // 17: publishTime
                "\"SELF_VISIBLE\" INTEGER NOT NULL ," + // 18: selfVisible
                "\"SHARE_DATE\" INTEGER NOT NULL ," + // 19: shareDate
                "\"SHARE_USER\" TEXT," + // 20: shareUser
                "\"SUPER_CHAPTER_ID\" INTEGER NOT NULL ," + // 21: superChapterId
                "\"SUPER_CHAPTER_NAME\" TEXT," + // 22: superChapterName
                "\"TITLE\" TEXT," + // 23: title
                "\"TYPE\" INTEGER NOT NULL ," + // 24: type
                "\"USER_ID\" INTEGER NOT NULL ," + // 25: userId
                "\"VISIBLE\" INTEGER NOT NULL ," + // 26: visible
                "\"ZAN\" INTEGER NOT NULL );"); // 27: zan
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"DATAS_BEAN\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, DatasBean entity) {
        stmt.clearBindings();
 
        String apkLink = entity.getApkLink();
        if (apkLink != null) {
            stmt.bindString(1, apkLink);
        }
        stmt.bindLong(2, entity.getAudit());
 
        String author = entity.getAuthor();
        if (author != null) {
            stmt.bindString(3, author);
        }
        stmt.bindLong(4, entity.getChapterId());
 
        String chapterName = entity.getChapterName();
        if (chapterName != null) {
            stmt.bindString(5, chapterName);
        }
        stmt.bindLong(6, entity.getCollect() ? 1L: 0L);
        stmt.bindLong(7, entity.getCourseId());
 
        String desc = entity.getDesc();
        if (desc != null) {
            stmt.bindString(8, desc);
        }
 
        String envelopePic = entity.getEnvelopePic();
        if (envelopePic != null) {
            stmt.bindString(9, envelopePic);
        }
        stmt.bindLong(10, entity.getFresh() ? 1L: 0L);
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(11, id);
        }
 
        String link = entity.getLink();
        if (link != null) {
            stmt.bindString(12, link);
        }
 
        String niceDate = entity.getNiceDate();
        if (niceDate != null) {
            stmt.bindString(13, niceDate);
        }
 
        String niceShareDate = entity.getNiceShareDate();
        if (niceShareDate != null) {
            stmt.bindString(14, niceShareDate);
        }
 
        String origin = entity.getOrigin();
        if (origin != null) {
            stmt.bindString(15, origin);
        }
 
        String prefix = entity.getPrefix();
        if (prefix != null) {
            stmt.bindString(16, prefix);
        }
 
        String projectLink = entity.getProjectLink();
        if (projectLink != null) {
            stmt.bindString(17, projectLink);
        }
        stmt.bindLong(18, entity.getPublishTime());
        stmt.bindLong(19, entity.getSelfVisible());
        stmt.bindLong(20, entity.getShareDate());
 
        String shareUser = entity.getShareUser();
        if (shareUser != null) {
            stmt.bindString(21, shareUser);
        }
        stmt.bindLong(22, entity.getSuperChapterId());
 
        String superChapterName = entity.getSuperChapterName();
        if (superChapterName != null) {
            stmt.bindString(23, superChapterName);
        }
 
        String title = entity.getTitle();
        if (title != null) {
            stmt.bindString(24, title);
        }
        stmt.bindLong(25, entity.getType());
        stmt.bindLong(26, entity.getUserId());
        stmt.bindLong(27, entity.getVisible());
        stmt.bindLong(28, entity.getZan());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, DatasBean entity) {
        stmt.clearBindings();
 
        String apkLink = entity.getApkLink();
        if (apkLink != null) {
            stmt.bindString(1, apkLink);
        }
        stmt.bindLong(2, entity.getAudit());
 
        String author = entity.getAuthor();
        if (author != null) {
            stmt.bindString(3, author);
        }
        stmt.bindLong(4, entity.getChapterId());
 
        String chapterName = entity.getChapterName();
        if (chapterName != null) {
            stmt.bindString(5, chapterName);
        }
        stmt.bindLong(6, entity.getCollect() ? 1L: 0L);
        stmt.bindLong(7, entity.getCourseId());
 
        String desc = entity.getDesc();
        if (desc != null) {
            stmt.bindString(8, desc);
        }
 
        String envelopePic = entity.getEnvelopePic();
        if (envelopePic != null) {
            stmt.bindString(9, envelopePic);
        }
        stmt.bindLong(10, entity.getFresh() ? 1L: 0L);
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(11, id);
        }
 
        String link = entity.getLink();
        if (link != null) {
            stmt.bindString(12, link);
        }
 
        String niceDate = entity.getNiceDate();
        if (niceDate != null) {
            stmt.bindString(13, niceDate);
        }
 
        String niceShareDate = entity.getNiceShareDate();
        if (niceShareDate != null) {
            stmt.bindString(14, niceShareDate);
        }
 
        String origin = entity.getOrigin();
        if (origin != null) {
            stmt.bindString(15, origin);
        }
 
        String prefix = entity.getPrefix();
        if (prefix != null) {
            stmt.bindString(16, prefix);
        }
 
        String projectLink = entity.getProjectLink();
        if (projectLink != null) {
            stmt.bindString(17, projectLink);
        }
        stmt.bindLong(18, entity.getPublishTime());
        stmt.bindLong(19, entity.getSelfVisible());
        stmt.bindLong(20, entity.getShareDate());
 
        String shareUser = entity.getShareUser();
        if (shareUser != null) {
            stmt.bindString(21, shareUser);
        }
        stmt.bindLong(22, entity.getSuperChapterId());
 
        String superChapterName = entity.getSuperChapterName();
        if (superChapterName != null) {
            stmt.bindString(23, superChapterName);
        }
 
        String title = entity.getTitle();
        if (title != null) {
            stmt.bindString(24, title);
        }
        stmt.bindLong(25, entity.getType());
        stmt.bindLong(26, entity.getUserId());
        stmt.bindLong(27, entity.getVisible());
        stmt.bindLong(28, entity.getZan());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 10) ? null : cursor.getLong(offset + 10);
    }    

    @Override
    public DatasBean readEntity(Cursor cursor, int offset) {
        DatasBean entity = new DatasBean( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // apkLink
            cursor.getInt(offset + 1), // audit
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // author
            cursor.getInt(offset + 3), // chapterId
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // chapterName
            cursor.getShort(offset + 5) != 0, // collect
            cursor.getInt(offset + 6), // courseId
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // desc
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8), // envelopePic
            cursor.getShort(offset + 9) != 0, // fresh
            cursor.isNull(offset + 10) ? null : cursor.getLong(offset + 10), // id
            cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11), // link
            cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12), // niceDate
            cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13), // niceShareDate
            cursor.isNull(offset + 14) ? null : cursor.getString(offset + 14), // origin
            cursor.isNull(offset + 15) ? null : cursor.getString(offset + 15), // prefix
            cursor.isNull(offset + 16) ? null : cursor.getString(offset + 16), // projectLink
            cursor.getLong(offset + 17), // publishTime
            cursor.getInt(offset + 18), // selfVisible
            cursor.getLong(offset + 19), // shareDate
            cursor.isNull(offset + 20) ? null : cursor.getString(offset + 20), // shareUser
            cursor.getInt(offset + 21), // superChapterId
            cursor.isNull(offset + 22) ? null : cursor.getString(offset + 22), // superChapterName
            cursor.isNull(offset + 23) ? null : cursor.getString(offset + 23), // title
            cursor.getInt(offset + 24), // type
            cursor.getInt(offset + 25), // userId
            cursor.getInt(offset + 26), // visible
            cursor.getInt(offset + 27) // zan
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, DatasBean entity, int offset) {
        entity.setApkLink(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setAudit(cursor.getInt(offset + 1));
        entity.setAuthor(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setChapterId(cursor.getInt(offset + 3));
        entity.setChapterName(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setCollect(cursor.getShort(offset + 5) != 0);
        entity.setCourseId(cursor.getInt(offset + 6));
        entity.setDesc(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setEnvelopePic(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
        entity.setFresh(cursor.getShort(offset + 9) != 0);
        entity.setId(cursor.isNull(offset + 10) ? null : cursor.getLong(offset + 10));
        entity.setLink(cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11));
        entity.setNiceDate(cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12));
        entity.setNiceShareDate(cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13));
        entity.setOrigin(cursor.isNull(offset + 14) ? null : cursor.getString(offset + 14));
        entity.setPrefix(cursor.isNull(offset + 15) ? null : cursor.getString(offset + 15));
        entity.setProjectLink(cursor.isNull(offset + 16) ? null : cursor.getString(offset + 16));
        entity.setPublishTime(cursor.getLong(offset + 17));
        entity.setSelfVisible(cursor.getInt(offset + 18));
        entity.setShareDate(cursor.getLong(offset + 19));
        entity.setShareUser(cursor.isNull(offset + 20) ? null : cursor.getString(offset + 20));
        entity.setSuperChapterId(cursor.getInt(offset + 21));
        entity.setSuperChapterName(cursor.isNull(offset + 22) ? null : cursor.getString(offset + 22));
        entity.setTitle(cursor.isNull(offset + 23) ? null : cursor.getString(offset + 23));
        entity.setType(cursor.getInt(offset + 24));
        entity.setUserId(cursor.getInt(offset + 25));
        entity.setVisible(cursor.getInt(offset + 26));
        entity.setZan(cursor.getInt(offset + 27));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(DatasBean entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(DatasBean entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(DatasBean entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
